#!/usr/bin/env ruby
# encoding: utf-8
# ./new helper script to create new posts using jekyll

require 'erb'
def render_template(title)
  # The DATA comes from whatever is beneath the END block at the bottom of the page
  ERB.new(DATA.read, _safe_level = nil, _trim_mode = true).result(binding)
end

title = ARGV.join(" ")
filepath = File.join("_posts", "#{Time.now.strftime('%Y-%m-%d')}-#{title.downcase.gsub(/[^a-z0-9-]+/,'-').gsub(/^-+|-+$/, '')}.md")
if File.exists?(filepath)
  puts <<-EOS
  We don't want to overwrite your unsaved changes now, do we?
  Delete the file at #{filepath} and run this again.
  Here is a command for you:
  rm "#{filepath}"
  EOS
  exit(-1)
end

File.write(filepath, render_template(title))

puts "created file: #{filepath}"

# whatever comes after the END marker is used as the ERB template in the
# render_template function
__END__
---
layout: post
title: "<%= title %>"
date: <%= Time.now.strftime('%Y-%m-%d %H:%M:%S') %>
comments: true
canonical_url: "..."
tags:
categories:
  - monkey
---

Go ahead and write something awesome! You can do it!!!

- - -
P.S: I'd love to hear your feedback on [sprymesh which is a simple web host backed by Dropbox Synchronization](https://sprymesh.com)

